version: '3.8'

services:
 web:
  build:
   context: .
  ports:
  - 8000:8000
  volumes:
  - ./:/app

 postgresdb:
  image: postgres
  ports:
  - 5432:5432
  environment:
  - POSTGRES_PASSWORD=peri54ri7end